model: cnn1d
# 数据集
data_path: dataset/0925class  # 数据集路径
class_labels: ["angry-愤怒","Delate-删除的","disgust-厌恶蔑视","fear-恐惧担忧","happy-喜悦","sad-悲伤","surprised-惊讶","TS-师生互动"]  # 情感标签
casia_name: ["liuchanhg","wangzhe","zhaoquanyin","ZhaoZuoxiang"]
dataset_name: 0925class
# 特征存储
feature_path: features/  # 特征存储路径
train_feature_path: features/train_0925.csv  # 训练特征存储路径
#predict_feature_path: features/test_class_opensmile_ravdess_IS10.csv  # 预测特征存储路径
test_class_path: features/test_0925.csv
# Opensmile 配置，只在 'feature_method: o' 时 需要设置
opensmile_config: IS10_paraling  # Opensmile 标准特征集
opensmile_path: opensmile-3.0-win-x64/opensmile-3.0-win-x64/  # Opensmile 安装路径

# checkpoints
checkpoint_path: checkpoints/  # checkpoint 存储路径
checkpoint_name: 0925class  # checkpoint 文件名

# 训练参数
epochs: 100 # 训练 epoch 数
batch_size: 32  # 批大小
lr: 0.0001  # 学习率
result_path : result/predict_0925_path.csv
result_path2 : result/predict_0925_result.csv
# 模型参数
n_kernels: 32  # 卷积核数量（每个卷积层都一样）
kernel_sizes: [5, 5]  # 每个卷积层的卷积核大小，列表长度为卷积层数量
dropout: 0.5
hidden_size: 32
